# Generated by Django 5.0.2 on 2024-02-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_rename_user_id_diary_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
